- name: composer
  src: geerlingguy.composer
  version: 1.7.0

- name: ntp
  src: geerlingguy.ntp
  version: 1.6.0

- name: logrotate
  src: nickhammond.logrotate
  version: e7a498d

- name: swapfile
  src: tersmitten.swapfile
  version: v2.0.6

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.3
